version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: manoj
      POSTGRES_PASSWORD: manoj123
      POSTGRES_DB: pulsefeed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pulsefeed-net

  backend:
    build: .
    container_name: pulsefeed_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pulsefeed
      SPRING_DATASOURCE_USERNAME: manoj
      SPRING_DATASOURCE_PASSWORD: manoj123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - pulsefeed-net

networks:
  pulsefeed-net:

volumes:
  postgres_data:
